### ISSUE TITLE
ROMTOOL.PY error: FileNotFoundError: [Errno 2] No such file or directory: '../build/roms.uf2'

### ISSUE THREAD

**Issue by 0ddjob** [mattcallow/CPC_PICOROM#2]
Hi again Matt

(sorry, don't have your email address - mine is in the About section on my [YT channel](www.youtube.com/@Brfff))

I couldn't find many ROM files (well, didn't spend very long looking ... unfortunately people seem to classify any vintage computer software as a "rom"), but I've got a few.

Unfortunately the Python script isn't happy that ROMS.UF2 file doesn't already exist:

```
brett@Bretts-MacBook-Air romtool % python3 romtool.py
Added rom # 0 at offset 0x00001000: type 0x40, size 16384 CPC 464 OS
Added rom # 1 at offset 0x00005000: type 0x40, size 16384 CPC 664 OS
Added rom # 2 at offset 0x00009000: type 0x40, size 16384 CPC 6128 OS
Added rom #10 at offset 0x00029000: type 0x80, size 16384 Locomotive BASIC 1.0
Added rom #11 at offset 0x0002d000: type 0x80, size 16384 Basic 1.1
Added rom #12 at offset 0x00031000: type 0x80, size 16384 Basic 1.1 (6128)
Added rom #30 at offset 0x00079000: type 0x01, size 16384 PICO ROM
Added rom #31 at offset 0x0007d000: type 0x01, size 16384 MAXAM 1.5
Added rom #35 at offset 0x0008d000: type 0x01, size 16384 Programmer's Toolbox
Start address is 0x1001e000
Traceback (most recent call last):
  File "/Users/brett/Documents/GitHub/CPC_PICOROM/romtool/romtool.py", line 208, in <module>
    image2uf2(buf, config['OUTPUT']['romfile'], __ROM_START) 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brett/Documents/GitHub/CPC_PICOROM/romtool/romtool.py", line 101, in image2uf2
    with open(outfile, 'wb') as f:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../build/roms.uf2'
```

Any chance you had a batch of ROMs handy that you could share, strictly for testing purposes of course.

Thanks

Brett.

**Comment by Felipe-Rafael-Rosa** [comment]
try this
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
If you don't have the c compliator, install it.(gcc or clang)

**Comment by mattcallow** [comment]
I think it's probably complaining because the build directory does not exist.

**Comment by 0ddjob** [comment]
Yep - you were too quick!  Just went out to feed the bunnies, tried something else, then realised I had created the "build" directory in the wrong place.

Worked now!  I'll check out the link you sent.  Thanks

```
Added rom # 0 at offset 0x00001000: type 0x40, size 16384 CPC 464 OS
Added rom # 1 at offset 0x00005000: type 0x40, size 16384 CPC 664 OS
Added rom # 2 at offset 0x00009000: type 0x40, size 16384 CPC 6128 OS
Added rom #10 at offset 0x00029000: type 0x80, size 16384 Locomotive BASIC 1.0
Added rom #11 at offset 0x0002d000: type 0x80, size 16384 Basic 1.1
Added rom #12 at offset 0x00031000: type 0x80, size 16384 Basic 1.1 (6128)
Added rom #30 at offset 0x00079000: type 0x01, size 16384 PICO ROM
Added rom #31 at offset 0x0007d000: type 0x01, size 16384 MAXAM 1.5
Added rom #35 at offset 0x0008d000: type 0x01, size 16384 Programmer's Toolbox
Start address is 0x1001e000
image size is 593920
created ../build/roms.uf2
Adding CONFIG0
Adding CONFIG1
Adding CONFIG2
Adding CONFIG3
Adding CONFIG4
Adding CONFIG5
Adding CONFIG6
Start address is 0x101ff000
image size is 4096
created ../build/config.uf2
brett@Bretts-MacBook-Air romtool % cd ..
brett@Bretts-MacBook-Air CPC_PICOROM % cd build 
brett@Bretts-MacBook-Air build % ls -al
total 4672
drwxr-xr-x   5 brett  staff      160 19 Sep 20:36 .
drwxr-xr-x  20 brett  staff      640 19 Sep 20:36 ..
-rw-r--r--   1 brett  staff     8192 19 Sep 20:36 config.uf2
-rw-r--r--   1 brett  staff  1196032 19 Sep 20:36 roms+config.uf2
-rw-r--r--   1 brett  staff  1187840 19 Sep 20:36 roms.uf2
```

**Comment by mattcallow** [comment]
I changed the code to create the directory if it doesn't exist.
